### ISSUE TITLE
Does not work with Python 3.9

### ISSUE THREAD

**Issue by goll72** [GeorgeHJ/albumart-ueber#13]
The script does not work with Python 3.9, ueberzug returns 
```
Task exception was never retrieved
future: <Task finished name='Task-7' coro=<shutdown() done, defined at /usr/lib/python3.9/site-packages/ueberzug/layer.py:88> exception=AttributeError("type object '_asyncio.Task' has no attribute 'all_tasks'")>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ueberzug/layer.py", line 89, in shutdown
    tasks = [task for task in asyncio.Task.all_tasks()
AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'
```

**Comment by GeorgeHJ** [comment]
Thanks for raising this. I suspect that this might be an upstream issue.

I'm not on Python 3.9 yet. Do you use Arch, btw? If you've built Überzug from the AUR then you might need to make sure you've rebuilt it since upgrading Python. Please just could you check this to confirm that this isn't a case of dependency mismatch?

I'm on Manjaro so all things equal I could have this break on me very soon, too!

**Comment by goll72** [comment]
I think this could also be a bug in Ueberzug or simply a change caused by the Python 3.8 to 3.9 upgrade, because now there is a bug in Ranger: If Ueberzug is being used to display images, and then you exit Ranger, the image will continue open.
![image](https://user-images.githubusercontent.com/70584620/101077610-d4ac9480-3583-11eb-806b-b3262afbe3ca.png)
![image](https://user-images.githubusercontent.com/70584620/101077676-eb52eb80-3583-11eb-81f0-ae02bf9a73ee.png)

**Comment by GeorgeHJ** [comment]
Very possible, but you might get lucky rebuilding if you're using an Arch-based distro. Have you tried this?

**Comment by goll72** [comment]
I tried both the AUR version, the PIP version, and the latest GIT version, none of them worked, they returned the same error.
I should notice that I am on Artix, and there was a delay to update all Python packages to 3.9, but now all of the python-* packages should be updated.
I also tried installing the latest release of Ueberzug (release 18.1.4, which was in August 16th of 2019), but, of course, the Python 3.9 modules are incompatible with that Ueberzug release.

**Comment by goll72** [comment]
Also, one thing to note, is that the script works for showing images (if the script was started with MPD already playing a song; the issue comes when changing state from no song playing to song playing or changing from a song to another song, where the image does not get updated.
![image](https://user-images.githubusercontent.com/70584620/101080044-0a06b180-3587-11eb-9140-ccc5abc511bb.png)
![image](https://user-images.githubusercontent.com/70584620/101080101-1d198180-3587-11eb-977c-d8549d6e05d1.png)

The cover art of the second song is actually:
![image](https://user-images.githubusercontent.com/70584620/101080156-2f93bb00-3587-11eb-8f9d-96006fde1755.png)

**Comment by GeorgeHJ** [comment]
Assuming that the code executed is the same as on master, the logic looks something like this:

```python
#layer.py (88-93)

async def shutdown(loop):
    tasks = [task for task in asyncio.Task.all_tasks()
             if task is not asyncio.tasks.Task.current_task()]
    list(map(lambda task: task.cancel(), tasks))
    await asyncio.gather(*tasks, return_exceptions=True)
    loop.stop()
```

I don't really know about this library so I might have to wait until this breaks on me and then try to hack my way out of it....

Do you happen to know the version in the Artix repos? Or does it use the Arch repo? https://repology.org/project/ueberzug/versions

**Comment by goll72** [comment]
In Ueberzug's case the package is pulled from the Arch's community repo. It is currently at version 18.1.6-3.

**Comment by GeorgeHJ** [comment]
https://www.archlinux.org/packages/community/any/ueberzug/

**Comment by GeorgeHJ** [comment]
@goll72 looks like Arch has the new version, does this fix your issue?

**Comment by goll72** [comment]
It still doesn't work

**Comment by GeorgeHJ** [comment]
Thanks for confirming. Please can I just check which method you are using for accessing artwork?

My solution for embedded artwork is particularly hacky and there are some new `mpd` features that I am thinking about leveraging in the future anyway...

**Comment by goll72** [comment]
What do you mean?

**Comment by GeorgeHJ** [comment]
Is the artwork embedded in your music files, or are you using something like `folder.jpg` or similar?

**Comment by goll72** [comment]
The artwork is embedded in the music files.

**Comment by GeorgeHJ** [comment]
Thanks for confirming.

It looks like there's movement upstream in relation to this: [#127](https://github.com/seebye/ueberzug/issues/127)

I will look to close when I can confirm that I can't reproduce on Python 3.9.

**Comment by goll72** [comment]
I tried do patch the file according to the PR specified in that issue. Now it's behaving even more weirdly: it does not work, but now I don't get any kind of error. I will try to mess with the script and see if I can get somewhere. (I use a modified version of your script, so that could be to blame as well, although I did test on your original script and it didn't work anyway)

**Comment by goll72** [comment]
Ueberzug's 18.1.8-1 release officially fixes the error. I tested it with this version and it is working now.

**Comment by GeorgeHJ** [comment]
That's great!

I'm planning on implementing a verbose output mode soon.

Please could you let me know what you like to modify? Is it just for music
directory?

I'm hoping to add some options.

**Comment by goll72** [comment]
I edited your script to more easily get debug output, you just have to change the out variable; I also removed features I don't use, such as tmux support:

[album-ueber.txt](https://github.com/GeorgeHJ/albumart-ueber/files/5680095/album-ueber.txt)

**Comment by GeorgeHJ** [comment]
Nice 😀. Thanks for the feedback here.

I came at it from another direction and added a new `$verbose` variable.

```bash
# Verbose output
verbose=true albumart-ueber.bash

# Trace output
verbose=true bash -x albumart-ueber.bash
```

You can then stream `stderr` anywhere you like.

**Comment by goll72** [comment]
It stopped working again, now with another error message:

```
Traceback (most recent call last):
  File "/usr/bin/ueberzug", line 33, in <module>
    sys.exit(load_entry_point('ueberzug==18.1.8', 'console_scripts', 'ueberzug')())
  File "/usr/lib/python3.9/site-packages/ueberzug/__main__.py", line 55, in main
    module.main(options)
  File "/usr/lib/python3.9/site-packages/ueberzug/layer.py", line 226, in main
    with windows, image_loader:
  File "/usr/lib/python3.9/site-packages/ueberzug/batch.py", line 128, in __enter__
    return BatchList([instance.__enter__() for instance in self])
  File "/usr/lib/python3.9/site-packages/ueberzug/batch.py", line 128, in <listcomp>
    return BatchList([instance.__enter__() for instance in self])
  File "/usr/lib/python3.9/site-packages/ueberzug/ui.py", line 166, in __enter__
    self.draw()
  File "/usr/lib/python3.9/site-packages/ueberzug/ui.py", line 180, in draw
    self.parent_info.calculate_sizes(
  File "/usr/lib/python3.9/site-packages/ueberzug/terminal.py", line 68, in calculate_sizes
    self.__calculate_sizes(self.pty, fallback_width, fallback_height)
  File "/usr/lib/python3.9/site-packages/ueberzug/terminal.py", line 74, in __calculate_sizes
    cols, rows, xpixels, ypixels = TerminalInfo.get_size(fd_pty)
  File "/usr/lib/python3.9/site-packages/ueberzug/terminal.py", line 19, in get_size
    fretint = fcntl.ioctl(fd_pty, termios.TIOCGWINSZ, farg)
OSError: [Errno 25] Inappropriate ioctl for device
```

PS: python-wheel has been updated since then, I think it could be causing the problem.

**Comment by GeorgeHJ** [comment]
Did this happen with the move from 18.1.7 to 18.1.8?

**Comment by goll72** [comment]
It's working again now.
